### ISSUE TITLE
video#pinda-neural obstruction

### ISSUE THREAD

**Issue by P-eMartin** [ccp-eva/matt#311]
The video#pinda-neural layer may obstruct choices. 
![image](https://github.com/ccp-eva/matt/assets/36887778/82068f1d-0381-4559-9f96-73bf8357c4b2)

**Comment by P-eMartin** [comment]
Taken into account when introduction.ts is run once.

**Comment by kalaschnik** [comment]
Correct, this usually happens when you subset the procedure (which should only happen during development).

As in your screenshot either the pinda video element or the pinda neutral video element [overlay](https://github.com/ccp-eva/matt/blob/ddf67fe48aaf90987a16e28740e391691f16538d/src/app.html#L18) the experiment [wrapper](https://github.com/ccp-eva/matt/blob/ddf67fe48aaf90987a16e28740e391691f16538d/src/app.html#L22)

If you have an eventListener listening for an [ended event](https://github.com/ccp-eva/matt/blob/ddf67fe48aaf90987a16e28740e391691f16538d/src/procedure/sIntroduction.ts#L74C3-L74C3) this does not occor:
